POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "Test",
  "email": "test@email.com",
  "password": "Pa$$w0rd"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "Pa$$w0rd"
}

###

GET http://localhost:8080/test/auth/required
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUZXN0IiwiaWF0IjoxNzEzNzA4MTYzLCJleHAiOjE3MTM3MTE3NjN9.JELtult5nPd2uAEFmi9Nwo_x1ywMv8IEfmj3c49icpk

###

GET http://localhost:8080/test/auth/optional

###

GET http://localhost:8080/test/auth/optional
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUZXN0IiwiaWF0IjoxNzEzNzA4MTYzLCJleHAiOjE3MTM3MTE3NjN9.JELtult5nPd2uAEFmi9Nwo_x1ywMv8IEfmj3c49icpk