POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "Test",
  "password": "Pa$$w0rd"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "Test",
  "password": "Pa$$w0rd"
}

###

GET http://localhost:8080/test/auth/required
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUZXN0IiwiaWF0IjoxNzEzNzA2MTAwLCJleHAiOjE3MTM3MDk3MDB9.tF1IfJW4OZd4AA0wSd0eN6rp4KlTiTbqE3PUNitdJVo

###

GET http://localhost:8080/test/auth/optional

###

GET http://localhost:8080/test/auth/optional
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUZXN0IiwiaWF0IjoxNzEzNzA2MTAwLCJleHAiOjE3MTM3MDk3MDB9.tF1IfJW4OZd4AA0wSd0eN6rp4KlTiTbqE3PUNitdJVo