version: "3"
services:
  wip-be:
    image: wip-be
    ports:
      - "8080:8080"
    networks:
      - internal
    restart: always
  mongodb:
    image: mongo:7.0.8
    ports:
      - "27017:27017"
    volumes:
      - C:/mongodb/wip-be-data:/data/db
    networks:
      - internal
    restart: always
  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    networks:
      - internal
    restart: always
networks:
  internal:
